---
- hosts: windows-byod-client

  vars_files:
    - vars/generic.yml

  tasks:
    - name: Get network adapter name
      win_shell: |
        $output = (Get-NetIPConfiguration |Where-Object {$_.IPv4Address.IPAddress.Length -gt 0 }|Select-Object -First 1).InterfaceAlias
        Write-Host $output -NoNewLine
      register: nic_name
  
    - name: DNS Client
      win_dns_client:
        adapter_names: '{{ nic_name.stdout }}'
        ipv4_addresses: "{{ dns_client_dns_server_ip }}"
      when: dns_client_configure