---
- hosts: windows-dc

  vars_files:
    - vars/generic.yml

  tasks:

    - name: include generic roles
      include_role:
        name: "{{ item }}"
      with_items:
        - ansible-role-win-disable-firewall
        - ansible-role-win-disable-windows-updates
        - ansible-role-win-language
        - ansible-role-win-hostname
        - ansible-role-win-disable-password-complexity
        - ansible-role-win-domain

    - name: DC - DNS Service ListenAddresses
      win_regedit:
        path: HKLM:\SYSTEM\CurrentControlSet\Services\DNS\Parameters
        name: ListenAddresses
        data: '[''{{ dns_client_dns_server_ip }}'']'
        type: multistring
      notify: restart DNS

    - name: Check DNS Forwarders
      win_shell: |
        $forwarders = Get-DnsServerForwarder
        if (($forwarders).IPAddress.Length -gt 0)
        {
          if (($forwarders).IPAddress[0].IPAddressToString -ne "8.8.8.8")
          {
            Write-Host "false"
          }
          else
          {
            Write-Host "true"
          }
        }
        else 
        {
          Write-Host "true"
        }
      register: dnsforwarder_ok
      changed_when: false
    
    - name: Remove DNS Forwarders
      win_shell: |
        Remove-DnsServerForwarder -IPAddress (Get-DnsServerForwarder).IPAddress -Passthru -Confirm:$false -Force
      when: dnsforwarder_ok.stdout is not match("true")
      
    - name: Add DNS Forwarders 8.8.8.8
      win_shell: |
        Add-DnsServerForwarder -IPAddress 8.8.8.8 -PassThru -Confirm:$false
      when: dnsforwarder_ok.stdout is not match("true")

    - name: Add DNS Forwarders 8.8.4.4
      win_shell: |
        Add-DnsServerForwarder -IPAddress 8.8.4.4 -PassThru -Confirm:$false
      when: dnsforwarder_ok.stdout is not match("true")

    - name: restart DNS
      win_service:
        name: DNS
        state: restarted
      when: dnsforwarder_ok.stdout is not match("true")


  handlers:
    - name: restart DNS
      win_service:
        name: DNS
        state: restarted
