---
# generic setup of vm's
- import_playbook: 10-windows-generic.yml
- import_playbook: 10-dc-generic.yml
# create ad ous, groups and users
- import_playbook: 20-dc-ad-configuration.yml

- import_playbook: 10-domainmembers-generic.yml

- import_playbook: 10-rdsh-generic.yml
- import_playbook: 10-domainclient-generic.yml
- import_playbook: 10-byod-generic.yml

# prepare install share on DC
- import_playbook: 20-dc-resources.yml


# prepare install sources on DC
- import_playbook: 50-dc-bisf.yml
- import_playbook: 50-dc-devicetrust.yml
- import_playbook: 50-dc-fslogix.yml

# prepare device trust certified architect training sources on DC
- import_playbook: 51-dc-devicetrust-training.yml

# install apps on session hosts
- import_playbook: 50-rdsh-bisf.yml
- import_playbook: 50-rdsh-devicetrust.yml
- import_playbook: 50-rdsh-fslogix.yml

# install apps on clients
- import_playbook: 50-client-devicetrust.yml
